# Generated by Django 2.0.3 on 2018-04-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='name',
            new_name='college_name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='studentname',
        ),
        migrations.AddField(
            model_name='student',
            name='college_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.College'),
        ),
    ]
