# Generated by Django 2.0.3 on 2018-04-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180417_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentname',
            new_name='student_name',
        ),
    ]
